### ISSUE TITLE
imports gvpy

### ISSUE THREAD

**Issue by jessecusack** [gunnarvoet/spmlib#1]
Hey Gunnar,
I'm getting an error importing spmlib because it imports gvpy (in plt.py), is this a personal repo of yours or another dependency?
Jesse

**Comment by gunnarvoet** [comment]
Yes, this is my own little collection of python tools at https://github.com/gunnarvoet/pythonlib <https://github.com/gunnarvoet/pythonlib>. Thought I had the code cleaned from it to make it easier on others...

Let me get rid of this dependency for now.

-Gunnar

**Comment by gunnarvoet** [comment]
ok, I think I got this resolved. Let me know if you are still having problems.

plt.py is more or less a placeholder at this time but I thought it would be nice to collect some common methods here, like extracting a vertical section along a shiptrack to mimic ctd sections.

**Comment by jessecusack** [comment]
That fixed it, I could run all your notebook code too. If I make any useful additions I'll submit a pull request.

**Comment by gunnarvoet** [comment]
Great! Excited to actually be using this platform collaboratively :)
